a = input("a = ");
b = input("b = ");
z = -2:0.1:2;
beta = -pi:pi/12:pi;
r = a.*((z+b).^2).*log(z+b);
[Z,Beta] = meshgrid(z,beta);
x = r.*sin(Beta);
y = r.*cos(Beta);
z = Z;
surf(x,y,z);
title("гиперболо-логарифмическая поверхность");