syms n x;
disp("first");
otv1 = symsum(1/(n+1)^2,n,0,inf);
disp(otv1);
disp("third");
otv2 = symsum(1./(x-n).^3,n,-inf,+inf);
disp(otv2);
disp("fifth");
otv3 =symsum(x.^n,n,0,inf);
disp(otv3);